---
- name: "Initialize MariaDB {{ mysql_user }} user."
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    check_implicit_admin: true
    login_user: "{{ user_mysql }}" 
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    state: present
    priv: "*.*:ALL,GRANT"