---
- name: Set PyMySQL package name.
  ansible.builtin.set_fact:
    pymysql_pkg_opts: {
      "Debian" : "python3-pymysql",
      "Archlinux" : "python-pymysql",
      "RedHat" : "python3-PyMySQL"
    }

- name: Install PyMySQL package.
  ansible.builtin.package:
    name: "{{ [ansible_facts.os_family] | map('extract', pymysql_pkg_opts) | first | default('python3-pymysql') }}"
    state: present
