---
- name: Place temporary cnf file.
  ansible.builtin.template:
    src: templates/temp.cnf.j2
    dest: /etc/my.cnf
    mode: '0644'

- name: Get temp root password.
  ansible.builtin.shell: >-
    grep 'temporary password' /var/log/mysqld.log |
    awk '{print $NF}' | tail -n 1
  register: temp_root_pw

- name: Set root password.
  ansible.builtin.shell: >-
    mariadb-admin -uroot
    --password="{{ temp_root_pw.stdout }}"
    password "{{ mysql_root_password }}" proc

- name: Set "{{ mysql_user }}" user and password.
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL,GRANT'
    update_password: always
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Make sure /etc/mysql exists.
  ansible.builtin.file:
    path: /etc/mysql/
    state: directory

- name: Copy root.cnf.
  ansible.builtin.template:
    src: root.cnf.j2
    dest: /etc/mysql/root.cnf
    mode: '0600'
    owner: root
    group: root

- name: Make symlink of file for root db access.
  ansible.builtin.file:
    state: link
    src: /etc/mysql/root.cnf
    path: /root/.my.cnf

- name: Delete anonymous connections.
  community.mysql.mysql_user:
    name: ""
    host_all: true
    login_user: root
    state: absent

- name: Ensure test database is removed.
  community.mysql.mysql_db:
    name: test
    login_user: root
    state: absent

- name: Stop MariaDB again.
  ansible.builtin.service:
    name: mariadb
    state: stopped
    enabled: true

- name: Remove mysqld log file.
  ansible.builtin.file:
    path: /var/log/mysqld.log
    state: absent

- name: Ensure MariaDB is started.
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
