---
- name: Set possible mysqld.sockets.
  ansible.builtin.set_fact:
    socks: ["/var/run/mysqld/mysqld.sock", "/run/mysqld/mysqld.sock", "/var/lib/mysql/mysql.sock"]

- name: Check which mysqld sockets exist.
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items: "{{ socks }}"
  register: valid_socks

- name: Configure mysqld.socket.
  ansible.builtin.set_fact:
    mysqld:
      socket: "{{ valid_socks.results[0].item }}"
  no_log: true
