---
- name: Allow SQL traffic in default zone
  ansible.posix.firewalld:
    service: mysql
    permanent: true
    state: enabled

- name: Allow Guacamole WebUI traffic in default zone
  ansible.posix.firewalld:
    port: "{{ webui_port }}/tcp"
    permanent: true
    state: enabled

- name: Restart firewall for changes to take effect.
  ansible.builtin.service:
    name: firewalld
    state: restarted
  become: true
