---
- name: Check if Guacamole folder exists.
  ansible.builtin.stat:
    path: "{{ guacamole_dir }}"
  register: guac_dir

- name: Create Guacamole folder.
  ansible.builtin.file:
    path: "{{ guacamole_dir }}"
    state: directory
  when: not guac_dir.stat.exists

- name: Copy Docker Compose.
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ guacamole_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Ensure Guacamole is running.
  community.docker.docker_compose_v2:
    project_src: "{{ guacamole_dir }}/"
    build: never
