---
- name: Check if MariaDB is already present.
  ansible.builtin.command: which mariadb
  failed_when: false
  changed_when: false
  check_mode: false
  register: mariadb_command_result

- name: Install MariaDB.
  ansible.builtin.package:
    name: mariadb-server
    state: present
  when: mariadb_command_result.rc != 0

- name: Ensure dependencies are met.
  ansible.builtin.import_tasks: configure_mariadb/dependencies.yml

# Arch gets mad if you try to start the service and don't do this
- name: Initialize SQL for Archlinux.
  ansible.builtin.shell: >-
    mariadb-install-db --user={{ user_mysql }} --basedir=/usr --datadir=/var/lib/mysql
  when: 
    - ansible_facts.os_family == 'Archlinux'
    - mariadb_command_result.rc != 0

- name: Ensure MariaDB is started.
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Configure mysqld.socket.
  ansible.builtin.include_tasks: configure_mariadb/mysqld.yml
  when: mariadb_command_result.rc != 0

- name: Configure MariaDB.
  ansible.builtin.include_tasks: configure_mariadb/init_mariadb.yml
  when: mariadb_command_result.rc != 0
