---
- name: Set possible architectures
  ansible.builtin.set_fact:
    deb_arch: {
      "armv6l": "armhf",
      "armv7l": "armhf",
      "aarch64": "arm64",
      "x86_64": "amd64",
      "i386": "i386"
    }

- name: Add Docker apt repository.
  block:
    - name: Dowload the Docker apt key. 
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Set distribution value.
      block:
        - name: Set Debian distribution to options.
          ansible.builtin.set_fact:
            deb_opts: {
              "ubuntu" : "ubuntu",
              "raspbian" : "raspbian",
            }

        - name: Identify which Debian option to pull.
          ansible.builtin.set_fact:
            deb_opt: "{{ [ansible_distribution|lower] | map('extract', deb_opts) | first | default('debian') }}"

    - name: Add the Docker repository to the list of apt repositories.
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ deb_arch[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ deb_opt }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

- name: Install Docker.
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  