---
- name: Ensure dnf-utils is installed.
  ansible.builtin.dnf:
    name: dnf-utils
    state: present

- name: Set distribution value.
  block:
    - name: Set RedHat distribution to options.
      ansible.builtin.set_fact:
        rhel_opts: {
          "centos" : "centos",
          "fedora" : "fedora",
        }

    - name: Identify which RedHat option to pull.
      ansible.builtin.set_fact:
        rhel_opt: "{{ [ansible_distribution|lower] | map('extract', rhel_opts) | first | default('rhel') }}"

- name: Add the Docker repository.
  ansible.builtin.shell: >-
    dnf config-manager --add-repo https://download.docker.com/linux/{{ rhel_opt }}/docker-ce.repo
  args:
    creates: /etc/dnf.repos.d/docker-ce.repo 

- name: Install Docker.
  ansible.builtin.dnf:
    update_cache: true
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
